### ISSUE TITLE
Inconsistent method format flags

### ISSUE THREAD

**Issue by janvrany** [powerlang/powerlang#18]
`CompiledMethod` format flags definition differer between Bee-DMR and powerlang, see:

https://github.com/powerlang/bee-dmr/blob/1658d211c927513c135df20e5bac5fd434888443/Kernel/CompiledMethod.st#L31-L42
```
CompiledMethod class >> initializeFormatFlags [
	Flags := PoolDictionary newConstantPool.
	Flags
		at: 'ArgCount' put: (1 thru: 6);
		at: 'BlockCount' put: (7 thru: 17);
		at: 'TempCount' put: (18 thru: 28);
		at: 'TypeField' put: (29 thru: 31);
		at: 'EnvCount' put: (32 thru: 42);
		at: 'Debuggable' put: (1 bitShift: 28);
		at: 'DMR' put: (1 bitShift: 29);
		at: 'HasBlock' put: (1 bitShift: 30)
]
```

and

https://github.com/powerlang/powerlang/blob/bcc976d2d925eb68d7e05eab781b1cebdf6dca52/bootstrap/src/Powerlang-Core/SCompiledMethodFlags.class.st#L18-L27

**Comment by melkyades** [comment]
fixed in [this commit](https://github.com/powerlang/bee-dmr/commit/f9866a861aa9fedbcd37c108880863b9c2d0451b) in bee-dmr repo
