### ISSUE TITLE
Discussion about removing pointers from native code

### ISSUE THREAD

**Issue by melkyades** [powerlang/powerlang#3]
The idea is to make the native code not hold any pointer. This would simplify not only gc, but anying related to tracing the object graph like allInstances, allReferences, etc. because we would avoid the special case for objects that are bytearrays but hold pointers and must be traced.

The native code uses pointers for (at least) the following things: 
- The compiled method
- send sites
- nil, true, false
- method literals
- Closure and Array classes (for creating instances)

We could make the compiled method be put in a register (M) using rip-relative addressing. Then, method literals can be accessed through method pointer in the register. SendSites would need to be added as literals as well. Nil, true and false and other special objects could go to an array of "fast objects" that is stored in a register. I would recommend having nil, true and false always in registers (callee saved like r12, r13, r14 in amd64).

The remaining problem is how to maintain the compiled method in the register during/after a send. We can use the same approach than with self, restore it from the stack of the caller. In that case we would have something like:
```
prologue:
    push rbp
    mov rbp, rsp
    push rsi          ; load self register
    mov rbx, [rip+offset] ; load M register (needs patching if this code is moved)
    push rbx
[...]
access literal:
   mov rcx, [rbx+index*8]   ; (instead of mov rcx, oop)
[...]

epilogue:
   mov rsp, rbp
   pop rbp
   mov rsi, [rbp-offset_self]
   mov rbx, [rbp-offset_method]
   ret
```

Is it worth? From design, looks fine, for performance? Not sure, but seems okish: new literal load is encoded with 4 bytes instead of 10, but is indirect, so we stress processor's data cache but free code cache. The added instr to restore M is 5 bytes long and accesses stack (memory)

**Comment by janvrany** [comment]
> Not sure, but seems okish: new literal load is encoded with 4 bytes instead of 10, but is indirect, so we stress processor's data cache but free code cache. The added instr to restore M is 5 bytes long and accesses stack (memory)

I do not think this analysis makes much sense, to be honest. We need to think and design beyond AMD64. For example, on RISC-V load 64 bit immediate can be up to 6 instructions. Not only that - you may need to patch the value time to time when GC moves it. Patching 3 or 6 instructions is tricky - it is hard to do it atomically and even if you can do it, not all architectures provide I-cache consistency like AMD64. For example, on RISC-V you need manually to synchronize all cores when you change instruction memory. IIRC, on AArch64 some instructions are patchable, some not. Things like this.

**Comment by melkyades** [comment]
> do not think this analysis makes much sense, to be honest. We need to think and design beyond AMD64. 

Well I have to get into the details of other ISAs but the analysis on amd64 makes sense to me as the starting point. In any case please add more info regarding other ISAs. On the other hand, changes made to the format of native code should not bloat amd64, which is one of the main targets where the code should run.

> For example, on RISC-V load 64 bit immediate can be up to 6 instructions. Not only that - you may need to patch the value time to time when GC moves it. Patching 3 or 6 instructions is tricky - it is hard to do it atomically and even if you can do it, not all architectures provide I-cache consistency like AMD64. For example, on RISC-V you need manually to synchronize all cores when you change instruction memory.

I agree, it can be tricky, and that's the reason why I opened this issue. In any case, from what I've seen in other jit implementations, you'd never write addresses with a variable set of instructions, you just assume a worse case and then generate a fixed list of instructions. Then, when patching, you can overwrite each field corresponding to each part of the address. You can abstract all this with some api (i.e. arch patchAddressAtOffset: o with: address) that does the complicated things, like filling the fields and flushing caches in a different way for each architecture.

Still, not having to patch native code seems like a much simpler design, so I think we should go for that option
