### ISSUE TITLE
Unable to compiler launcher

### ISSUE THREAD

**Issue by KenDickey** [powerlang/powerlang#34]
Greetings,

Just discovered PowerLang.

Tried 
 cmake -B build
but cmake does not recognize "-B".

Too early daze ?

[make.out.txt](https://github.com/powerlang/powerlang/files/5876478/make.out.txt)

Thanks much,
-KenD

**Comment by janvrany** [comment]
I have (hopefully) fixed that in PR #35.  Let's hope it will get merged soon.

**Comment by janvrany** [comment]
Just merged #35. Hope it fixes the issue.

**Comment by KenDickey** [comment]
Well, we now die for a different reason.

[make2.out.txt](https://github.com/powerlang/powerlang/files/5907687/make2.out.txt)

**Comment by janvrany** [comment]
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- broken
> CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCXXCompiler.cmake:45 (message):
>  The C++ compiler
>
>   "/usr/bin/c++"
>
>  is not able to compile a simple test program.
>
>  It fails with the following output:

This looks like an issue with toolchain on your side. 

> /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_4cc11.dir/link.txt --verbose=1
>    "" qc libcmTC_4cc11.a  CMakeFiles/cmTC_4cc11.dir/testCXXCompiler.cxx.o
>    Error running link command: No such file or directory

Some issue with linker?

**Comment by KenDickey** [comment]
"" qc libcmTC_e5401.a  CMakeFiles/cmTC_e5401.dir/testCXXCompiler.cxx.o

Looks like '""' above should be 'ar'

OpenSmalltalk builds w/o problem, so tools seem to work. [NB: script kiddy here; not really a C/make user]

Any idea what I should look for?  cmake debug flag to set?

**Comment by KenDickey** [comment]
Tried different Linux distro (AntiX vs Mint; amd64 again; don't use Intel CPUs much).

Same result.

[CMakeCache.txt](https://github.com/powerlang/powerlang/files/5913990/CMakeCache.txt)
[CMakeError.log](https://github.com/powerlang/powerlang/files/5913991/CMakeError.log)
[CMakeOutput.log](https://github.com/powerlang/powerlang/files/5913992/CMakeOutput.log)

**Comment by melkyades** [comment]
Looking in history I saw that I added a line to launcher/CMakeLists.txt so that `ar` worked on Windows. Can you try commenting that `SET(CMAKE_AR "ar")` to see if it works? I cannot remember why it didn't work in Windows (what version of ar was it looking for?) and neither know what is the default in Ubuntu (maybe clang instead of gcc one?)
