### ISSUE TITLE
CI should test building of launcher too

### ISSUE THREAD

**Issue by melkyades** [powerlang/powerlang#38]
The CI is only running tests inside the pharo bootstrapper image. We should configure the CI to also test building of the launcher and even running some Smalltalk code with it.

**Comment by janvrany** [comment]
No, not on Linux:

https://github.com/powerlang/powerlang/blob/master/.github/workflows/blank.yml#L31-L40

**Comment by melkyades** [comment]
great! I didn't see that. Why only linux? did the others fail?

**Comment by janvrany** [comment]
@melkyades 
I did not want to spend time on debugging builds I have no access to. If you want to give it a go, it would be nice to have it, indeed.

**Comment by melkyades** [comment]
done
