### ISSUE TITLE
Missing $^  ??

### ISSUE THREAD

**Issue by KenDickey** [powerlang/powerlang#42]
In Powerlang-Core/SParseTreeVisitor.class.st:

vvv===vvv
{ #category : #visiting }
SParseTreeVisitor >> visitForeignNode: anForeignNode [
	self visitLiteral: anForeignNode
]
^^^===^^^

I am expecting a ^/return here..

See? Someone _does_ read your code!  ;^)

**Comment by melkyades** [comment]
Good catch. We don't have any sender of `visitForeignNode:` yet to check, but I think your suggestion is correct, so we should change it.

btw I'm really glad you are looking at the code, I plan to restart doing improvements soon.
