### ISSUE TITLE
BaselineOfPowerlang has some weird dependency problem since Pharo 9

### ISSUE THREAD

**Issue by melkyades** [powerlang/powerlang#73]
We've been trying to generate a Pharo 9 image but it insists in loading Roassal even when specifying base group. Maybe it is a problem in Pharo, but I'm starting to think it is a problem in the definition of the baseline itself.

To reproduce, change the bootstrap/Makefile to fetch pharo 9 instead of 8, and you'll see how installing the base group pulls roassal and all of its dependencies.

I tried running the install manually with the lines below and got the same result:

```
Metacello new
        repository: 'tonel://./src';
        baseline: 'Powerlang';
        load: 'base'
```

**Comment by janvrany** [comment]
I had a look and have no idea whatsoever. So many things broke on Pharo 9. 

I did ask on Pharo discord, but no reply so far. Will see if something comes up in next couple of days.

**Comment by janvrany** [comment]
Okay, so the problem might be that Roassal is already pre-loaded in Pharo 9+ so we may need separate configs for Pharo 8 and Pharo 9. 
I have an idea how to do it, will have a look later. 

Thanks to Sebastian Jordan who pointed that out on Pharo Discord.

**Comment by melkyades** [comment]
Thank you very much Jan! I ran some tests on Pharo 9, some of them passed, one gave an error and then it crashed while debugging. I put that on #79, this one is done.
