### ISSUE TITLE
SParseNode >> nodesDo: aBlock includingDeclarations: aBoolean

### ISSUE THREAD

**Issue by KenDickey** [powerlang/powerlang#80]
I had a problem with:

    SParseNode >> nodesDo: aBlock includingDeclarations: aBoolean
            aBlock evaluateWith: self

    The base case of #evaluateWith seems to be a no-op.

    I get the desired result with:

    SParseNode >> nodesDo: aBlock includingDeclarations: aBoolean
            aBlock value: self

**Comment by melkyades** [comment]
Ok, this comes from a mechanism that allows some polymorphism with symbols in Bee. We don't need any of that in Powerlang codebase, would you mind pushing a commit that changes it to just `value:`, looking for other senders too? there shouldn't be many.

**Comment by KenDickey** [comment]
On 2022-10-07 02:18, Javier Pimas wrote:

> Ok, this comes from a mechanism that allows some polymorphism with 
> symbols in Bee. We don't need any of that in Powerlang codebase, would 
> you mind pushing a commit that changes it to just value:,

Actually?

So, fire up my old Intel box which I rarely use.  Fork Powerlang and 
clone it,  Bring it up in Pharo, which aside from Powerlang, I do not 
use.  Figure out how to write out the Tonel file from Pharo.  Then do a 
pull request?

This is a one line change.

Perhaps you could do it?

;^)
-KenD

**Comment by melkyades** [comment]
I've opened a branch that fixes this (jp/upgrade-pharo), could you @janvrany check that it works for your setup? you might also take the chance to have a look at issue #72, which is blocking loading of Powerlang into P10

**Comment by melkyades** [comment]
finally fixed powerlang to work in P9 in #87. #72 is still breaking P10.
